[ hFig, data ] = genDensityHist( 'Z:\Analysis\Cortico-Thalamic\Run 1 all\HeatMaps\thalamus',...
    'thalamus', {'AA0038','AA0039','AA0041'},...
    'ErrorProperties',[{{'Color','LineWidth'}},{{[1,0,0],1.5}}]);